version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  tomcat:
    restart: always
    image: 'tomcat:jdk8'
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/docker/tomcat/webapps:/usr/local/tomcat/webapps